### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by UmerZia** [letarulinda/mobile-version-setup#4]
Hello @letarulinda 👋 , You did excellent work so far 👍, Here are some issues which you can cover for a better user experience 😄.

- Kindly use the proper naming convention for image icons as well as alt of image tag.
- Kindly download and use .svg format icons for better image quality.
- Kindly add acknowledgment in your readme file.
- Kindly use font and CSS which are provided in the Figma template.
- Kindly fix the overlapping text of the description provided in the hero section.
- Kindly the margin for headings in the card.
- Kindly remove the scroll bar from social media icons in the hero section.
- Kindly remove the border around the card buttons to make it look like the provided Figma template.

Happy Coding 😃

**Comment by letarulinda** [comment]
Thanks for the Issues, I shall Implement them.

**Comment by Balikuddembe** [comment]
Hello @UmerZia , @letarulinda :Thank you for demonstrating the peer-to-peer code review concept.It was an excellent discussion.Let @letarulinda work on the above raised issues to make her code more excellent.
Thanks 👍
